/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ChatUi {}
}

declare global {


  interface HTMLChatUiElement extends Components.ChatUi, HTMLStencilElement {}
  var HTMLChatUiElement: {
    prototype: HTMLChatUiElement;
    new (): HTMLChatUiElement;
  };
  interface HTMLElementTagNameMap {
    'chat-ui': HTMLChatUiElement;
  }
}

declare namespace LocalJSX {
  interface ChatUi extends JSXBase.HTMLAttributes<HTMLChatUiElement> {
    'onEnd'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'chat-ui': ChatUi;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


